apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apiadmin
  name: apiadmin
spec:
  ports:
  - name: "3020"
    port: 3020
    targetPort: 3000
  selector:
    io.kompose.service: apiadmin
  type: NodePort
status:
  loadBalancer: {}
