apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiadmin
  labels:
    app: apiadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiadmin
  template:
    metadata:
      labels:
        app: apiadmin
    spec:
      containers:
      - name: apiadmin
        image: apiadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 30003
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always        
