apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apipns
  name: apipns
spec:
  ports:
  - name: "3011"
    port: 3011
    targetPort: 3000
  selector:
    io.kompose.service: apipns
  type: LoadBalancer
status:
  loadBalancer: {}
