apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apipns
  name: apipns
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apipns
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: apipns
        name: apipns
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
