apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    run: apisms
  name: apisms
  namespace: default
spec:
  ports:
  - name: "30001"
    port: 30001
    nodePort: 30001
    targetPort: 30001
  selector:
    run: apisms
    app: apisms  
  type: NodePort
status:
  loadBalancer: {}
