apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisms
  labels:
    app: apisms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apisms
  template:
    metadata:
      labels:
        app: apisms
    spec:
      containers: 
      - name: apisms
        image: apisms
        imagePullPolicy: Never
        ports:
        - containerPort: 30001
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always     