apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    run: mongopns
  name: mongopns
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mongopns
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: test
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        image: mongopns
        imagePullPolicy: Never
        name: mongopns
        ports:
        - containerPort: 30091
        resources: {}
      restartPolicy: Always
status: {}
