apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mongosms
  name: mongosms
spec:
  ports:
  - name: "27019"
    port: 27019
    targetPort: 27019
  selector:
    app: mongosms
  type: NodePort
status:
  loadBalancer: {}
