apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosms
  labels:
    app: mongosms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosms
  template:
    metadata:
      labels:
        app: mongosms
    spec:
      containers:
      - name: mongosms
        image: mongosms
        imagePullPolicy: Never
        ports:
        - containerPort: 30090
        env:
        - name: MONGO_INITDB_DATABASE
          value: test
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always      
