apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: movistar
  name: movistar
spec:
  ports:
  - name: "3002"
    port: 3002
    targetPort: 3000
  selector:
    io.kompose.service: movistar
  type: LoadBalancer
status:
  loadBalancer: {}
