apiVersion: apps/v1
kind: Deployment
metadata:
  name: movistarvip
  labels:
    app: movistarvip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movistarvip
  template:
    metadata:
      labels:
        app: movistarvip
    spec:
      containers:
      - name: movistarvip
        image: movistarvip
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always