apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mqpns
  name: mqpns
spec:
  ports:
  - name: "3004"
    port: 3004
    targetPort: 3000
  selector:
    io.kompose.service: mqpns
  type: LoadBalancer
status:
  loadBalancer: {}
