apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqsms
  labels:
    app: mqsms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqsms
  template:
    metadata:
      labels:
        app: mqsms
    spec:
      containers:
      - name: mqsms
        image: mqsms
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always