apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mqsms
  name: mqsms
spec:
  ports:
  - name: "3014"
    port: 3014
    targetPort: 3000
  selector:
    io.kompose.service: mqsms
  type: NodePort
status:
  loadBalancer: {}
