apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redissms
  name: redissms
spec:
  ports:
  - name: "6381"
    port: 6381
    targetPort: 6381
  selector:
    io.kompose.service: redissms
  type: LoadBalancer
status:
  loadBalancer: {}
