apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: ClusterIP
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redispns
  name: redispns
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redispns
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: redispns
        imagePullPolicy: Never
        name: redispns
        ports:
        - containerPort: 30081
        resources: {}
      restartPolicy: Always
status: {}
