apiVersion: apps/v1
kind: Deployment
metadata:
  name: redissms
  labels:
    app: redissms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redissms
  template:
    metadata:
      labels:
        app: redissms
    spec:
      containers:
      - name: redissms
        image: redissms
        imagePullPolicy: Never
        ports:
        - containerPort: 30080
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always