apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: retriespns
  name: retriespns
spec:
  ports:
  - name: "3010"
    port: 3010
    targetPort: 3000
  selector:
    io.kompose.service: retriespns
  type: LoadBalancer
status:
  loadBalancer: {}
