apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    run: retriespns
  name: retriespns
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: retriespns
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: kubernetes
        image: retriespns
        imagePullPolicy: Never
        name: retriespns
        ports:
        - containerPort: 30006
        resources: {}
      restartPolicy: Always
status: {}
