apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    run: retriessms
  name: retriessms
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: retriessms
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: kubernetes
        image: retriessms
        imagePullPolicy: Never
        name: retriessms
        ports:
        - containerPort: 30005
        resources: {}
      restartPolicy: Always
status: {}
