apiVersion: apps/v1
kind: Deployment
metadata:
  name: vodafone
  labels:
    app: vodafone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vodafone
  template:
    metadata:
      labels:
        app: vodafone
    spec:
      containers:
      - name: vodafone
        image: vodafone
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always