version: "3.1"

services:
#apipns
   #Optional you can create the docker image  (# docker build -t name) .
  apipns: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: apipns
    container_name: "apipns"      
    restart: always
    ports:
      - 30002:30002
    
    environment:
      NODE_ENV: "docker"
    labels:
     kompose.service.type: NodePort # labels for kompose convert to kubernetes
     kompose.image-pull-policy: Never # labels for kompose convert to kubernetes
    links:
      - redispns
      - mongopns
    depends_on:
      - redispns
      - mongopns