  #vodafone
   #Optional you can create the docker image  (# docker build -t name) .
  vodafone: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: vodafone
    container_name: "vodafone"      
    restart: always
    ports:
      - 3016:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
