  #apiadmin
   #Optional you can create the docker image  (# docker build -t name) .
  apiadmin: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: apiadmin
    container_name: "apiadmin"      
    restart: always
    ports:
      - 30003:30003
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
      kompose.image-pull-policy: Never
