  #redisconf
   #Optional you can create the docker image  (# docker build -t name) .
  redisconf: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: redisconf
    container_name: "redisconf"      
    restart: always
    ports:
      - 3007:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
