  #mqsms
   #Optional you can create the docker image  (# docker build -t name) .
  mqsms: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: mqsms
    container_name: "mqsms"      
    restart: always
    ports:
      - 3014:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
