apiVersion: apps/v1
kind: Deployment
metadata:
  name: apistatusback
  labels:
    app: apistatusback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apistatusback
  template:
    metadata:
      labels:
        app: apistatusback
    spec:
      containers:
      - name: apistatusback
        image: apistatusback
        imagePullPolicy: Never
        ports:
        - containerPort: 30004
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always