apiVersion: apps/v1
kind: Deployment
metadata:
  name: batchpns
  labels:
    app: batchpns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batchpns
  template:
    metadata:
      labels:
        app: batchpns
    spec:
      containers: 
      - name: batchpns
        image: batchpns
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always     