apiVersion: apps/v1
kind: Deployment
metadata:
  name: google
  labels:
    app: google
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google
  template:
    metadata:
      labels:
        app: google
    spec:
      containers:
      - name: google
        image: google
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always