apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsoft
  labels:
    app: microsoft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microsoft
  template:
    metadata:
      labels:
        app: microsoft
    spec:
      containers:
      - name: microsoft
        image: microsoft
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always