apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongopns
  labels:
    app: mongopns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongopns
  template:
    metadata:
      labels:
        app: mongopns
    spec:
      containers:
      - name: mongopns
        image: mongopns
        imagePullPolicy: Never
        ports:
        - containerPort: 30091
        env:
        - name: MONGO_INITDB_DATABASE
          value: test
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always      
