apiVersion: apps/v1
kind: Deployment
metadata:
  name: movistar
  labels:
    app: movistar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movistar
  template:
    metadata:
      labels:
        app: movistar
    spec:
      containers:
      - name: movistar
        image: movistar
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always