apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqpns
  labels:
    app: mqpns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqpns
  template:
    metadata:
      labels:
        app: mqpns
    spec:
      containers:
      - name: mqpns
        image: mqpns
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always