apiVersion: apps/v1
kind: Deployment
metadata:
  name: orange
  labels:
    app: orange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orange
  template:
    metadata:
      labels:
        app: orange
    spec:
      containers:
      - name: orange
        image: orange
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always