apiVersion: apps/v1
kind: Deployment
metadata:
  name: redispns
  labels:
    app: redispns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redispns
  template:
    metadata:
      labels:
        app: redispns
    spec:
      containers:
      - name: redispns
        image: redispns
        imagePullPolicy: Never
        ports:
        - containerPort: 30081
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always