apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriessms
  labels:
    app: retriessms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retriessms
  template:
    metadata:
      labels:
        app: retriessms
    spec:
      containers:
      - name: retriessms
        image: retriessms
        imagePullPolicy: Never
        ports:
        - containerPort: 30005
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always