apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriespns
  labels:
    app: retriespns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retriespns
  template:
    metadata:
      labels:
        app: retriespns
    spec:
      containers:
      - name: retriespns
        image: retriespns
        imagePullPolicy: Never
        ports:
        - containerPort: 30006
        env:
        - name: NODE_ENV
          value: kubernetes
      restartPolicy: Always