  #apistatusback
   #Optional you can create the docker image  (# docker build -t name) .
  apistatusback: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: apistatusback
    container_name: "apistatusback"      
    restart: always
    ports:
      - 30004:30004
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: NodePort
      kompose.image-pull-policy: Never
