  #mqpns
   #Optional you can create the docker image  (# docker build -t name) .
  mqpns: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: mqpns
    container_name: "mqpns"      
    restart: always
    ports:
      - 3004:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
