  #apipns
   #Optional you can create the docker image  (# docker build -t name) .
  apipns: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: apipns
    container_name: "apipns"      
    restart: always
    ports:
      - 3011:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
