version: "3.1"

services:
  #orange
   #Optional you can create the docker image  (# docker build -t name) .
  orange: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: orange
    container_name: "orange"      
    restart: always
     
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: NodePort
      kompose.image-pull-policy: Never
    links:
      - redissms
      - mongosms
    depends_on:
      - redissms
      - mongosms