  #batchpns
   #Optional you can create the docker image  (# docker build -t name) .
  batchpns: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: batchpns
    container_name: "batchpns"      
    restart: always
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
      kompose.image-pull-policy: Never
