apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
     kompose.image-pull-policy: Never # labels for kompose convert to kubernetes
   kompose.service.type: NodePort # labels for kompose convert to kubernetes
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apisms
  name: apisms
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apisms
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: apisms
        imagePullPolicy: Never
        name: apisms
        ports:
        - containerPort: 30001
        resources: {}
      restartPolicy: Always
status: {}
