apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
     kompose.image-pull-policy: Never # labels for kompose convert to kubernetes
   kompose.service.type: NodePort # labels for kompose convert to kubernetes
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: apistatusback
  name: apistatusback
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apistatusback
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: apistatusback
        imagePullPolicy: Never
        name: apistatusback
        ports:
        - containerPort: 30004
        resources: {}
      restartPolicy: Always
status: {}
