apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: movistar
  name: movistar
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: movistar
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: docker
        image: movistar
        imagePullPolicy: Never
        name: movistar
        resources: {}
      restartPolicy: Always
status: {}
