apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.image-pull-policy: Never
    kompose.service.type: NodePort
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: redisconf
  name: redisconf
spec:
  ports:
  - name: "30082"
    port: 30082
    nodePort: 30082
  selector:
    io.kompose.service: redisconf
  type: NodePort
status:
  loadBalancer: {}
