version: "3.1"

services:
  #retriespns
   #Optional you can create the docker image  (# docker build -t name) .
  retriespns: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: retriespns
    container_name: "retriespns"      
    restart: always
    ports:
      - 30006:30006
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: NodePort
      kompose.image-pull-policy: 
    links:
      - redispns
      - mongopns
    depends_on:
      - redispns
      - mongopns