version: "3.1"

services:
:_apple_:
:_google_:
:_microsoft_:
:_movistar_:
:_movistarvip_:
:_vodafone_:  
:_orange_:
:_mqsms_:
:_mqpns_:
:_apiadmin_:
:_apisms_:
:_apipns_:
:_apistatusback_:
:_retriessms_:
:_retriespns_:
:_redispns_:
:_redissms_:
:_mongopns_:
:_mongosms_:
