'use strict';

/**
 * Autogenerated Service code by SnAPI framework - git:  https://github.com/oamat/nodejs
 *      SQL Lite Repository https://www.sqlitetutorial.net/sqlite-nodejs
 * 
 *
 * Author:  OAF 
 * git:  https://github.com/oamat/nodejs
 **/

 //Dependencies
 const utils = require('../utils/writer.js');
 const repository = require('../repositories/{{{repository_code}}}');
 
