'use strict';

/**
 * Autogenerated Repository code by SnAPI framework - git:  https://github.com/oamat/nodejs
 *      SQL Lite Repository https://www.sqlitetutorial.net/sqlite-nodejs
 * 
 *
 * Author:  OAF 
 * git:  https://github.com/oamat/nodejs
 **/


//Dependencies
const { db } = require('./sqllite_conn.js');
