apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mqsms
  name: mqsms
spec:
  ports:
  - name: "3014"
    port: 3014
    targetPort: 3000
  selector:
    io.kompose.service: mqsms
  type: LoadBalancer
status:
  loadBalancer: {}
