apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: orange
  name: orange
spec:
  ports:
  - name: "3015"
    port: 3015
    targetPort: 3000
  selector:
    io.kompose.service: orange
  type: LoadBalancer
status:
  loadBalancer: {}
