apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: console
  name: console
spec:
  ports:
  - name: "3003"
    port: 3003
    targetPort: 3000
  selector:
    io.kompose.service: console
  type: LoadBalancer
status:
  loadBalancer: {}
