apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: redispns
  name: redispns
spec:
  ports:
  - name: "3008"
    port: 3008
    targetPort: 3000
  selector:
    io.kompose.service: redispns
  type: LoadBalancer
status:
  loadBalancer: {}
