apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: redissms
  name: redissms
spec:
  ports:
  - name: "3009"
    port: 3009
    targetPort: 3000
  selector:
    io.kompose.service: redissms
  type: LoadBalancer
status:
  loadBalancer: {}
