apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: vodafone
  name: vodafone
spec:
  ports:
  - name: "3016"
    port: 3016
    targetPort: 3000
  selector:
    io.kompose.service: vodafone
  type: LoadBalancer
status:
  loadBalancer: {}
