version: "3.1"

services:
  #batchsms
   #Optional you can create the docker image  (# docker build -t name) .
  batchsms: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: batchsms
    container_name: "batchsms"      
    restart: always
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: NodePort
      kompose.image-pull-policy: Never
    links:
      - redissms
      - mongosms
    depends_on:
      - redissms
      - mongosms