  #movistar
   #Optional you can create the docker image  (# docker build -t name) .
  movistar: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: movistar
    container_name: "movistar"      
    restart: always
    ports:
      - 3002:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
