version: "3.1"

services:
  #movistar
   #Optional you can create the docker image  (# docker build -t name) .
  movistar: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: movistar
    container_name: "movistar"      
    restart: always
    
    environment:
      NODE_ENV: "docker"
    labels:
     kompose.service.type: NodePort # labels for kompose convert to kubernetes
     kompose.image-pull-policy: Never # labels for kompose convert to kubernetes
    links:
      - redissms
      - mongosms
    depends_on:
      - redissms
      - mongosms