version: "3.1"

services:
  #retriessms
   #Optional you can create the docker image  (# docker build -t name) .
  retriessms: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: retriessms
    container_name: "retriessms"      
    restart: always
    ports:
      - 30005:30005
    
    environment:
      NODE_ENV: "docker"
    labels:
     kompose.service.type: NodePort # labels for kompose convert to kubernetes
     kompose.image-pull-policy: Never # labels for kompose convert to kubernetes
    links:
      - redissms
      - redisconf
      - mongosms
    depends_on:
      - redissms
      - redisconf
      - mongosms