  #retriessms
   #Optional you can create the docker image  (# docker build -t name) .
  retriessms: 
    #build: . #build: Dockerfile #Optional : "build: ." Uses an image that’s built from the Dockerfile in the current directory.  
    image: retriessms
    container_name: "retriessms"      
    restart: always
    ports:
      - 3012:3000
    
    environment:
      NODE_ENV: "docker"
    labels:
      kompose.service.type: LoadBalancer
