apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Oriol\Downloads\Kubernetes\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    io.kompose.service: mongo-express
  type: LoadBalancer
status:
  loadBalancer: {}
