apiVersion: v1
kind: Service
metadata:
  name: mongo-tst-oasiss-oasiss   #SERVICE_NAME-${env}-${repoName}-${groupName}
  annotations:
    kompose.cmd: C:\Minikube\kompose.exe convert
    kompose.service.type: clusterIP
    kompose.version: 1.17.0 (a74acad)
  labels:
    k8s-app: oasiss-mongo-tst
    io.kompose.service: oasiss-mongo-tst 
spec:
  selector:
    k8s-app: oasiss-mongo-tst
    io.kompose.service: oasiss-mongo-tst
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  clusterIP: None
