apiVersion: v1
kind: Service
metadata:
  name: mongo-tst-oasiss-oasiss   #SERVICE_NAME-${env}-${repoName}-${groupName}
  labels:
    k8s-app: oasiss-mongo-tst
spec:
  selector:
    k8s-app: oasiss-mongo-tst
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  clusterIP: None
