apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-tst-oasiss-oasiss #SERVICE_NAME-${env}-${repoName}-${groupName}
  labels:
    k8s-app: oasiss-mongoexpress-tst
  annotations:
    d-engine.ip6n.net/backupBlock: "{{ blockId }}"
    d-engine.ip6n.net/ipv4: "auto"
    d-engine.ip6n.net/vs-http-desc: "HTTPS traffic to oasiss-mongoexpress"
    d-engine.ip6n.net/vs-http-vsPort: "8080"
    d-engine.ip6n.net/vs-http-template: "vs-tcp"
    d-engine.ip6n.net/vs-http-fwPermit: "0.0.0.0/0"
spec:
  selector:
    k8s-app: oasiss-mongoexpress-tst
  ports:
  - name: "8081"
    port: 8081 #8080 CXB
    protocol: TCP
    targetPort: 8081 #8080 CXB
  type: NodePort

