apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-tst-oasiss-deployment
  labels:    
    k8s-app: oasiss-mongoexpress-tst
    io.kompose.service: oasiss-mongoexpress-tst
  annotations:
    kompose.cmd: C:\Minikube\kompose.exe convert
    kompose.service.type: NodePort
    kompose.version: 1.17.0 (a74acad)
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oasiss-mongoexpress-tst
  strategy:
    type: Recreate
  template:
    metadata:
     labels:
        k8s-app: oasiss-mongoexpress-tst
        io.kompose.service: oasiss-mongoexpress-tst
    spec:
      containers:
      - name: oasiss-mongoexpress-tst
        image: mongo-express #pro-registry.pro.caas.caixabank.com/dockerhub/mongo-express:0.49 CXB
        ports:
        - containerPort: 8081 #8080 CXB
        env:
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: example
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: root
        - name:  ME_CONFIG_MONGODB_SERVER
          value: mongo-tst-oasiss-oasiss
      imagePullSecrets:
      - name: registry
