apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Oriol\Downloads\Kubernetes\kompose.exe convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nodeapirest
  name: nodeapirest
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: nodeapirest
  type: LoadBalancer
status:
  loadBalancer: {}
